# Unity test build
# Usage: make -f tests/Makefile.unity [test|clean]

CC      := gcc
CFLAGS  := -std=c99 -fPIC -pedantic -Wall -Wextra -Werror -I. -Isrc -Itests/unit -Itests/unit/mocks -DSYN_LOG_COLOR=1 -DSYN_USE_COREDUMP=1 -DSYN_COREDUMP_FLASH_ADDR=0 -DSYN_USE_TICKLESS=1 -DSYN_USE_DMA=1 -DSYN_USE_I2C_ASYNC=1 -DSYN_USE_SPI_ASYNC=1 -DSYN_FW_USE_HMAC=1 -DSYN_USE_MULTICORE=1 -DUNITY_INCLUDE_DOUBLE -DSYN_USE_METRICS=1 -DSYN_USE_ROUTER=1 -DSYN_USE_LIN=1 -DSYN_USE_IR=1 -DSYN_USE_SMBUS=1 -DSYN_USE_PMBUS=1 -DSYN_USE_MBUS=1 -DSYN_USE_DLT645=1 -DSYN_USE_AT_PARSER=1 -DSYN_USE_BACNET=1 -DSYN_USE_DEVICENET=1


# All SyntropicOS source files
SYN_SRCS := \
	src/syntropic/proto/syn_at_parser.c \
	src/syntropic/proto/syn_dlt645.c \
	src/syntropic/drivers/syn_gpio.c src/syntropic/drivers/syn_uart.c \
	src/syntropic/drivers/syn_adc.c src/syntropic/drivers/syn_exti.c \
	src/syntropic/drivers/syn_can.c src/syntropic/drivers/syn_soft_i2c.c \
	src/syntropic/drivers/syn_soft_spi.c src/syntropic/drivers/syn_sd.c \
	src/syntropic/drivers/syn_rtc.c src/syntropic/drivers/syn_soft_onewire.c \
	src/syntropic/drivers/syn_dac.c src/syntropic/drivers/syn_dma.c \
	src/syntropic/util/syn_ringbuf.c src/syntropic/util/syn_fsm.c \
	src/syntropic/util/syn_crc.c src/syntropic/util/syn_fmt.c \
	src/syntropic/util/syn_ramp.c src/syntropic/util/syn_scurve.c \
	src/syntropic/util/syn_cbor_write.c src/syntropic/util/syn_cbor_read.c \
	src/syntropic/util/syn_pubsub.c src/syntropic/util/syn_netbuf.c \
	src/syntropic/util/syn_spsc_queue.c src/syntropic/util/syn_slab.c \
	src/syntropic/sched/syn_sched.c src/syntropic/sched/syn_timer.c \
	src/syntropic/sched/syn_watchdog.c src/syntropic/sched/syn_sequencer.c \
	src/syntropic/sched/syn_workqueue.c src/syntropic/sched/syn_timer_wheel.c \
	src/syntropic/sched/syn_event_flags.c \
	src/syntropic/log/syn_log.c src/syntropic/log/syn_datalog.c src/syntropic/cli/syn_cli.c \
	src/syntropic/input/syn_button.c src/syntropic/input/syn_encoder.c \
	src/syntropic/output/syn_led.c src/syntropic/output/syn_soft_pwm.c \
	src/syntropic/dsp/syn_filter.c src/syntropic/dsp/syn_filter_design.c \
	src/syntropic/dsp/syn_signal.c src/syntropic/dsp/syn_biquad.c \
	src/syntropic/control/syn_pid.c src/syntropic/control/syn_autotune.c \
	src/syntropic/control/syn_control_stats.c \
	src/syntropic/motor/syn_stepper.c src/syntropic/motor/syn_servo.c \
	src/syntropic/motor/syn_dc_motor.c src/syntropic/motor/syn_motor_ctrl.c \
	src/syntropic/motor/syn_actuator.c \
	src/syntropic/proto/syn_cobs.c src/syntropic/proto/syn_modbus.c \
	src/syntropic/proto/syn_modbus_master.c \
	src/syntropic/proto/syn_canopen.c src/syntropic/proto/syn_cia402.c \
	src/syntropic/proto/syn_lss.c src/syntropic/proto/syn_cia401.c \
	src/syntropic/proto/syn_cia303.c \
	src/syntropic/proto/syn_dmx512.c \
	src/syntropic/proto/syn_ccp.c \
	src/syntropic/proto/syn_xcp.c \
	src/syntropic/proto/syn_uds.c \
	src/syntropic/proto/syn_devicenet.c \
	src/syntropic/proto/syn_isotp.c \
	src/syntropic/proto/syn_dali.c \
	src/syntropic/proto/syn_bacnet.c \
	src/syntropic/proto/syn_lin.c \
	src/syntropic/proto/syn_ir.c \
	src/syntropic/proto/syn_smbus.c \
	src/syntropic/proto/syn_pmbus.c \
	src/syntropic/proto/syn_mbus.c \
	src/syntropic/proto/syn_cjt188.c \
	src/syntropic/proto/syn_canopen_mgr.c src/syntropic/proto/syn_j1939.c \
	src/syntropic/proto/syn_n2k.c src/syntropic/proto/syn_ethercat.c \
	src/syntropic/sensor/syn_sensor.c src/syntropic/sensor/syn_sensor_fusion.c \
	src/syntropic/storage/syn_param.c \
	src/syntropic/storage/syn_settings.c \
	src/syntropic/debug/syn_trace.c src/syntropic/debug/syn_profiler.c \
	src/syntropic/debug/syn_task_profile.c \
	src/syntropic/dsp/syn_dds.c \
	src/syntropic/system/syn_boot.c src/syntropic/system/syn_errlog.c \
	src/syntropic/system/syn_power.c src/syntropic/system/syn_hwwdt.c \
	src/syntropic/system/syn_fwupdate.c src/syntropic/system/syn_fwboot.c \
	src/syntropic/display/syn_canvas.c src/syntropic/ui/syn_menu.c \
	src/syntropic/ui/syn_imgui.c \
	src/syntropic/net/syn_router.c src/syntropic/net/syn_heartbeat.c \
	src/syntropic/net/syn_http.c src/syntropic/net/syn_httpd.c \
	src/syntropic/net/syn_transport_tcp.c \
	src/syntropic/net/syn_websocket.c \
	src/syntropic/net/syn_tcp.c \
	src/syntropic/net/syn_udp.c \
	src/syntropic/net/syn_dns.c \
	src/syntropic/net/syn_mqtt.c \
	src/syntropic/util/syn_json_write.c src/syntropic/util/syn_json_read.c \
	src/syntropic/sched/syn_ao.c \
	src/syntropic/storage/syn_vfs.c \
	src/syntropic/storage/syn_lfs.c \
	src/syntropic/net/syn_coap.c \
	src/syntropic/dsp/syn_fft.c \
	src/syntropic/system/syn_fault.c \
	src/syntropic/util/syn_sha256.c \
	src/syntropic/util/syn_aes128.c \
	src/syntropic/system/syn_coredump.c \
	src/syntropic/crypto/syn_blake2s.c \
	src/syntropic/crypto/syn_chacha20poly1305.c \
	src/syntropic/crypto/syn_x25519.c \
	src/syntropic/net/syn_sntp.c \
	src/syntropic/util/syn_stream.c \
	src/syntropic/util/syn_backoff.c \
	src/syntropic/util/syn_random.c \
	src/syntropic/util/syn_metrics.c \
	src/syntropic/util/syn_qmath.c \
	src/syntropic/util/syn_matrix.c \
	src/syntropic/util/syn_quaternion.c \
	src/syntropic/util/syn_vector.c \
	src/syntropic/util/syn_transform.c \
	src/syntropic/dsp/syn_kalman.c src/syntropic/motor/syn_foc.c \
	src/syntropic/motor/syn_foc_observer.c \
	src/syntropic/proto/syn_modbus_tcp.c src/syntropic/proto/syn_nmea.c \
	src/syntropic/motor/syn_interpolator.c \
	src/syntropic/util/syn_geo.c \
	src/syntropic/drivers/syn_hpclock.c \
	src/syntropic/drivers/syn_timesync.c \
	src/syntropic/output/syn_buzzer.c \
	src/syntropic/input/syn_keypad.c \
	src/syntropic/input/syn_touch.c \
	src/syntropic/input/syn_dipswitch.c \
	src/syntropic/display/syn_charlcd.c \
	src/syntropic/display/syn_oled.c \
	src/syntropic/display/syn_seg7.c \
	src/syntropic/drivers/syn_shiftreg.c \
	src/syntropic/drivers/syn_ioexp.c \
	src/syntropic/input/syn_joystick.c \
	src/syntropic/sensor/syn_powermon.c \
	src/syntropic/sensor/syn_climate.c \
	src/syntropic/output/syn_smartled.c \
	src/syntropic/sensor/syn_distance.c \
	src/syntropic/sensor/syn_scale.c \
	src/syntropic/sensor/syn_lux.c \
	src/syntropic/drivers/syn_rfid.c \
	src/syntropic/sensor/syn_biometric.c \
	src/syntropic/motor/syn_bldc_6step.c \
	src/syntropic/proto/syn_sbus.c \
	src/syntropic/output/syn_dshot.c \
	src/syntropic/input/syn_ppm.c \
	src/syntropic/proto/syn_crsf.c \
	src/syntropic/proto/syn_ibus.c \
	src/syntropic/control/syn_rc_curve.c \
	src/syntropic/control/syn_rc_failsafe.c \
	src/syntropic/output/syn_dshot_telemetry.c \
	src/syntropic/control/syn_flight_pid.c \
	src/syntropic/proto/syn_msp.c \
	src/syntropic/proto/syn_mavlink.c \
	src/syntropic/log/syn_blackbox.c \
	src/syntropic/drivers/syn_usb_cdc.c \
	src/syntropic/net/syn_eth.c \
	src/syntropic/net/syn_dhcp.c \
	src/syntropic/net/syn_icmp.c \
	src/syntropic/net/syn_transport_udp.c \
	src/syntropic/net/syn_autoip.c \
	src/syntropic/net/syn_netcfg.c \
	src/syntropic/net/syn_igmp.c \
	src/syntropic/util/syn_nn.c \
	src/syntropic/util/syn_dsp.c

# Unity framework
UNITY_SRCS := tests/unit/unity/unity.c

# Mock port layer
MOCK_SRCS := tests/unit/mocks/mock_port.c

# Build output directory
BUILD_DIR := build/tests

# All per-module test files
TEST_SRCS := $(wildcard tests/unit/test_*.c)

ALL_SRCS := $(SYN_SRCS) $(UNITY_SRCS) $(MOCK_SRCS) $(TEST_SRCS)
OBJS     := $(patsubst %.c,$(BUILD_DIR)/%.o,$(ALL_SRCS))

.PHONY: all test test-cov clean

all: test

$(BUILD_DIR)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD_DIR)/test_unity: $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $@ -lm $(LDFLAGS)

test_unity: $(BUILD_DIR)/test_unity

test: test_unity
	./$(BUILD_DIR)/test_unity

test-cov: CFLAGS += --coverage
test-cov: LDFLAGS += --coverage
test-cov: test_unity
	@find . -name "*.gcda" -delete
	./$(BUILD_DIR)/test_unity
	@echo "Coverage data generated."

clean:
	rm -f test_unity test_unity_cov coverage.info coverage_src.info
	rm -rf coverage_html $(BUILD_DIR)
	find . \( -name "*.gcda" -o -name "*.gcno" -o -name "*.su" \) -delete
