# Unity test build
# Usage: make -f tests/Makefile.unity [test|clean]

CC      := gcc
CFLAGS  := -std=c99 -pedantic -Wall -Wextra -Werror -I. -Isrc -Itests/unit -Itests/unit/mocks -DSYN_LOG_COLOR=1 -DSYN_USE_COREDUMP=1 -DSYN_COREDUMP_FLASH_ADDR=0 -DSYN_USE_TICKLESS=1 -DSYN_USE_DMA=1 -DSYN_USE_I2C_ASYNC=1 -DSYN_USE_SPI_ASYNC=1 -DSYN_FW_USE_HMAC=1 -DSYN_USE_MULTICORE=1 -DUNITY_INCLUDE_DOUBLE -DSYN_USE_METRICS=1 -DSYN_USE_ROUTER=1 -DSYN_USE_LIN=1 -DSYN_USE_IR=1 -DSYN_USE_SMBUS=1 -DSYN_USE_PMBUS=1

# All SyntropicOS source files
SYN_SRCS := \
	src/syntropic/drivers/syn_gpio.c src/syntropic/drivers/syn_uart.c \
	src/syntropic/drivers/syn_adc.c src/syntropic/drivers/syn_exti.c \
	src/syntropic/drivers/syn_can.c src/syntropic/drivers/syn_soft_i2c.c \
	src/syntropic/drivers/syn_soft_spi.c src/syntropic/drivers/syn_sd.c \
	src/syntropic/drivers/syn_rtc.c src/syntropic/drivers/syn_soft_onewire.c \
	src/syntropic/drivers/syn_dac.c src/syntropic/drivers/syn_dma.c \
	src/syntropic/util/syn_ringbuf.c src/syntropic/util/syn_fsm.c \
	src/syntropic/util/syn_crc.c src/syntropic/util/syn_fmt.c \
	src/syntropic/util/syn_ramp.c src/syntropic/util/syn_scurve.c \
	src/syntropic/util/syn_cbor_write.c src/syntropic/util/syn_cbor_read.c \
	src/syntropic/util/syn_pubsub.c src/syntropic/util/syn_netbuf.c \
	src/syntropic/util/syn_spsc_queue.c src/syntropic/util/syn_slab.c \
	src/syntropic/sched/syn_sched.c src/syntropic/sched/syn_timer.c \
	src/syntropic/sched/syn_watchdog.c src/syntropic/sched/syn_sequencer.c \
	src/syntropic/sched/syn_workqueue.c src/syntropic/sched/syn_timer_wheel.c \
	src/syntropic/sched/syn_event_flags.c \
	src/syntropic/log/syn_log.c src/syntropic/log/syn_datalog.c src/syntropic/cli/syn_cli.c \
	src/syntropic/input/syn_button.c src/syntropic/input/syn_encoder.c \
	src/syntropic/output/syn_led.c src/syntropic/output/syn_soft_pwm.c \
	src/syntropic/dsp/syn_filter.c src/syntropic/dsp/syn_filter_design.c \
	src/syntropic/dsp/syn_signal.c src/syntropic/dsp/syn_biquad.c \
	src/syntropic/control/syn_pid.c src/syntropic/control/syn_autotune.c \
	src/syntropic/control/syn_control_stats.c \
	src/syntropic/motor/syn_stepper.c src/syntropic/motor/syn_servo.c \
	src/syntropic/motor/syn_dc_motor.c src/syntropic/motor/syn_motor_ctrl.c \
	src/syntropic/motor/syn_actuator.c \
	src/syntropic/proto/syn_cobs.c src/syntropic/proto/syn_modbus.c \
	src/syntropic/proto/syn_modbus_master.c \
	src/syntropic/proto/syn_canopen.c src/syntropic/proto/syn_cia402.c \
	src/syntropic/proto/syn_lss.c src/syntropic/proto/syn_cia401.c \
	src/syntropic/proto/syn_cia303.c \
	src/syntropic/proto/syn_dmx512.c \
	src/syntropic/proto/syn_isotp.c \
	src/syntropic/proto/syn_dali.c \
	src/syntropic/proto/syn_lin.c \
	src/syntropic/proto/syn_ir.c \
	src/syntropic/proto/syn_smbus.c \
	src/syntropic/proto/syn_pmbus.c \
	src/syntropic/proto/syn_canopen_mgr.c src/syntropic/proto/syn_j1939.c \
	src/syntropic/proto/syn_n2k.c \
	src/syntropic/sensor/syn_sensor.c src/syntropic/sensor/syn_sensor_fusion.c \
	src/syntropic/storage/syn_param.c \
	src/syntropic/storage/syn_settings.c \
	src/syntropic/debug/syn_trace.c src/syntropic/debug/syn_profiler.c \
	src/syntropic/debug/syn_task_profile.c \
	src/syntropic/dsp/syn_dds.c \
	src/syntropic/system/syn_boot.c src/syntropic/system/syn_errlog.c \
	src/syntropic/system/syn_power.c src/syntropic/system/syn_hwwdt.c \
	src/syntropic/system/syn_fwupdate.c src/syntropic/system/syn_fwboot.c \
	src/syntropic/display/syn_canvas.c src/syntropic/ui/syn_menu.c \
	src/syntropic/ui/syn_imgui.c \
	src/syntropic/net/syn_router.c src/syntropic/net/syn_heartbeat.c \
	src/syntropic/net/syn_http.c src/syntropic/net/syn_httpd.c \
	src/syntropic/net/syn_transport_tcp.c \
	src/syntropic/net/syn_websocket.c \
	src/syntropic/net/syn_dns.c \
	src/syntropic/net/syn_mqtt.c \
	src/syntropic/util/syn_json_write.c src/syntropic/util/syn_json_read.c \
	src/syntropic/sched/syn_ao.c \
	src/syntropic/storage/syn_vfs.c \
	src/syntropic/storage/syn_lfs.c \
	src/syntropic/net/syn_coap.c \
	src/syntropic/dsp/syn_fft.c \
	src/syntropic/system/syn_fault.c \
	src/syntropic/util/syn_sha256.c \
	src/syntropic/system/syn_coredump.c \
	src/syntropic/crypto/syn_blake2s.c \
	src/syntropic/crypto/syn_chacha20poly1305.c \
	src/syntropic/crypto/syn_x25519.c \
	src/syntropic/net/syn_sntp.c \
	src/syntropic/util/syn_stream.c \
	src/syntropic/util/syn_backoff.c \
	src/syntropic/util/syn_random.c \
	src/syntropic/util/syn_metrics.c \
	src/syntropic/util/syn_qmath.c \
	src/syntropic/util/syn_matrix.c \
	src/syntropic/util/syn_quaternion.c \
	src/syntropic/util/syn_vector.c \
	src/syntropic/util/syn_transform.c \
	src/syntropic/dsp/syn_kalman.c src/syntropic/motor/syn_foc.c \
	src/syntropic/motor/syn_foc_observer.c \
	src/syntropic/proto/syn_modbus_tcp.c src/syntropic/proto/syn_nmea.c \
	src/syntropic/motor/syn_interpolator.c

# Unity framework
UNITY_SRCS := tests/unit/unity/unity.c

# Mock port layer
MOCK_SRCS := tests/unit/mocks/mock_port.c

# All per-module test files
TEST_SRCS := $(filter-out tests/unit/test_timesync.c tests/unit/test_hpclock.c tests/unit/test_geo.c, $(wildcard tests/unit/test_*.c))

ALL_SRCS := $(SYN_SRCS) $(UNITY_SRCS) $(MOCK_SRCS) $(TEST_SRCS)

.PHONY: all test test-cov clean

all: test

test_unity: $(ALL_SRCS)
	$(CC) $(CFLAGS) $(ALL_SRCS) -o $@ -lm

test: test_unity
	./test_unity

test-cov: CFLAGS += --coverage
test-cov: clean test_unity
	./test_unity
	@echo "Coverage data generated (.gcda files)."

clean:
	rm -f test_unity test_unity_cov coverage.info coverage_src.info
	rm -rf coverage_html
	find . \( -name "*.gcda" -o -name "*.gcno" -o -name "*.su" \) -delete
