/**
 * @file main.c
 * @brief SyntropicOS ISO 15765-2 (ISO-TP) STM32 HAL Integration Example.
 *
 * Demonstrates non-blocking, zero-malloc ISO-TP multi-frame CAN transmission
 * and reception integrated directly with STM32 HAL CAN drivers (`HAL_CAN_...`).
 */

#include "syntropic/syntropic.h"
#include "stm32f4xx_hal.h"  /* Or stm32f1xx_hal.h / stm32g4xx_hal.h depending on target MCU */

/* Hardware CAN handle instance */
extern CAN_HandleTypeDef hcan1;

/* Static ISO-TP Link and buffers (zero dynamic allocation) */
static SYN_ISOTP_Link isotp_link;
static uint8_t rx_buffer[512];
static uint8_t tx_buffer[512];

/**
 * @brief Initialize ISO-TP link for diagnostic communication (UDS).
 */
void isotp_app_init(void)
{
    /*
     * Initialize link:
     *   - Rx CAN ID: 0x7E8 (incoming response from ECU)
     *   - Tx CAN ID: 0x7E0 (outgoing request to ECU)
     */
    syn_isotp_init(&isotp_link, 0x7E8, 0x7E0,
                   rx_buffer, sizeof(rx_buffer),
                   tx_buffer, sizeof(tx_buffer));

    /* Configure network layer timeouts (N_Bs = 1000ms, N_Cr = 1000ms) */
    syn_isotp_set_timeouts(&isotp_link, 1000, 1000);
}

/**
 * @brief STM32 HAL CAN Rx FIFO 0 Interrupt Callback.
 *
 * Invoked by STM32 HAL whenever a raw CAN frame arrives on FIFO 0.
 * Ingests raw frame into SyntropicOS ISO-TP engine.
 */
void HAL_CAN_RxFifo0MsgPendingCallback(CAN_HandleTypeDef *hcan)
{
    if (hcan->Instance == CAN1) {
        CAN_RxHeaderTypeDef rx_hdr;
        SYN_CAN_Frame frame;

        if (HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &rx_hdr, frame.data) == HAL_OK) {
            frame.id  = (rx_hdr.IDE == CAN_ID_STD) ? rx_hdr.StdId : rx_hdr.ExtId;
            frame.dlc = (uint8_t)rx_hdr.DLC;
#if defined(SYN_USE_CAN_FD) && SYN_USE_CAN_FD
            frame.is_fd = false;
#endif
            /* Feed frame into ISO-TP state machine */
            syn_isotp_process_rx_frame(&isotp_link, &frame);
        }
    }
}

/**
 * @brief Main application loop / task routine.
 *
 * Called periodically in main while(1) loop or scheduler task.
 */
void isotp_app_loop(uint32_t dt_ms)
{
    /* 1. Step ISO-TP timers (STmin, N_Bs, N_Cr) */
    syn_isotp_step(&isotp_link, dt_ms);

    /* 2. Drain and transmit all pending outgoing CAN frames generated by ISO-TP */
    SYN_CAN_Frame tx_frame;
    while (syn_isotp_get_tx_frame(&isotp_link, &tx_frame)) {
        CAN_TxHeaderTypeDef tx_hdr = {0};
        tx_hdr.StdId = tx_frame.id;
        tx_hdr.IDE   = CAN_ID_STD;
        tx_hdr.RTR   = CAN_RTR_DATA;
        tx_hdr.DLC   = tx_frame.dlc;

        uint32_t tx_mailbox;
        HAL_CAN_AddTxMessage(&hcan1, &tx_hdr, tx_frame.data, &tx_mailbox);
    }

    /* 3. Check if a complete assembled message has arrived */
    uint8_t payload[256];
    ssize_t len = syn_isotp_receive(&isotp_link, payload, sizeof(payload));
    if (len > 0) {
        /* Message complete! Process multi-byte UDS payload (e.g. 0x62 0xF1 0x90 ...) */
    }
}

/**
 * @brief Trigger transmission of a multi-byte diagnostic command.
 */
void send_uds_request(const uint8_t *cmd, size_t len)
{
    /* e.g. UDS ReadDataByIdentifier command (0x22, 0xF1, 0x90) */
    syn_isotp_send(&isotp_link, cmd, len);
}
