/**
 * @file stm32_uds_isotp_example.c
 * @brief SyntropicOS STM32 UDS (ISO 14229) over ISO-TP (ISO 15765-2) CAN Example.
 *
 * Demonstrates integrating UDS diagnostic server on STM32 using ISO-TP transport over CAN.
 * Supports DiagnosticSessionControl, SecurityAccess, ReadDataByIdentifier (RDBI),
 * WriteDataByIdentifier (WDBI), RoutineControl, and ECUReset.
 */

#include "syntropic/drivers/syn_can.h"
#include "syntropic/log/syn_log.h"
#include "syntropic/proto/syn_isotp.h"
#include "syntropic/proto/syn_uds.h"
#include "syntropic/sched/syn_sched.h"

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#define STM32_UDS_RX_CAN_ID 0x7E0U
#define STM32_UDS_TX_CAN_ID 0x7E8U

/* UDS Server Instance Context */
static SYN_UDS_Server g_uds;

/* ISO-TP Transport Instance Context & Buffers */
static SYN_ISOTP_Link g_isotp;
static uint8_t g_rx_buf[256];
static uint8_t g_tx_buf[256];

/* Scheduler & Task Handles */
static SYN_Task g_uds_task;
static SYN_Sched g_sched;

/* Shared DID Memory Buffers */
static uint8_t g_vin_did[17] = "SYN1234567890ABCD";
static uint8_t g_battery_volts[2] = {0x00, 0x78}; /* 12.0 Volts */

/* Simulated CAN hardware receive hook */
static void on_can_frame_received(uint32_t can_id, const uint8_t data[8], uint8_t len)
{
    if (can_id == STM32_UDS_RX_CAN_ID) {
        SYN_CAN_Frame frame;
        frame.id = can_id;
        frame.dlc = (len > 8) ? 8 : len;
        memcpy(frame.data, data, frame.dlc);
        syn_isotp_process_rx_frame(&g_isotp, &frame);
    }
}

/* Periodic 10ms task servicing ISO-TP transport & UDS request processing */
static PT_THREAD(app_10ms_task(SYN_Task *task))
{
    PT_BEGIN(&task->pt);

    /* Step ISO-TP timers */
    syn_isotp_step(&g_isotp, 10);

    /* Drain pending outgoing CAN frames generated by ISO-TP engine */
    SYN_CAN_Frame tx_frame;
    while (syn_isotp_get_tx_frame(&g_isotp, &tx_frame)) {
        syn_can_send(0, tx_frame.id, tx_frame.data, tx_frame.dlc);
    }

    /* Check if full UDS request payload received over ISO-TP */
    uint8_t req_buf[256];
    ssize_t req_len = syn_isotp_receive(&g_isotp, req_buf, sizeof(req_buf));
    if (req_len > 0) {
        uint8_t resp_buf[256];
        uint16_t resp_len = 0;

        /* Process UDS diagnostic request */
        if (syn_uds_process_request(&g_uds, req_buf, (uint16_t)req_len, resp_buf,
                                    sizeof(resp_buf), &resp_len)) {
            /* Transmit UDS response over ISO-TP multi-frame transport */
            syn_isotp_send(&g_isotp, resp_buf, resp_len);
        }
    }

    PT_END(&task->pt);
}

void stm32_uds_isotp_example_init(void)
{
    (void)on_can_frame_received;

    /* Initialize UDS Server */
    syn_uds_init(&g_uds);

    /* Register Data Identifiers (DIDs) */
    syn_uds_register_did(&g_uds, 0xF190U, g_vin_did, sizeof(g_vin_did), false); /* VIN (RO) */
    syn_uds_register_did(&g_uds, 0x0100U, g_battery_volts, sizeof(g_battery_volts),
                         true); /* Batt Volts (RW) */

    /* Initialize ISO-TP Link */
    syn_isotp_init(&g_isotp, STM32_UDS_RX_CAN_ID, STM32_UDS_TX_CAN_ID, g_rx_buf, sizeof(g_rx_buf),
                   g_tx_buf, sizeof(g_tx_buf));

    /* Initialize task and scheduler */
    syn_task_create(&g_uds_task, "uds_isotp_task", app_10ms_task, 1, NULL);
    syn_sched_init(&g_sched, &g_uds_task, 1);

    SYN_LOG_INFO("STM32 UDS Server (ISO 14229 over ISO 15765-2) initialized on CAN RX:0x%03X TX:0x%03X",
                 STM32_UDS_RX_CAN_ID, STM32_UDS_TX_CAN_ID);
}
