name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Build & Run Containerized Suite
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Containerized Code Formatting Check
        run: |
          make container-format

      - name: Run Containerized Unit Tests
        run: |
          make container-test

