name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Build & Run Containerized Suite
    runs-on: ubuntu-latest

    env:
      CONTAINER_ENGINE: docker
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Pre-build Testing Container Image
        run: |
          make -C tools/containers container-build

      - name: Run Containerized Code Formatting Check
        run: |
          make container-format

      - name: Run Containerized Unit Tests & Coverage
        run: |
          make container-test

